project:
  type: website

website:
  title: "MSB105"
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: "Home"
      - about.qmd
      - text: "Introduksjon"
        menu: 
          - 000_introduction/001_intro.qmd
          - 000_introduction/005_undervisningsplan.qmd
          - 000_introduction/pref-setup-2022/ps2022.qmd
          - 005_lecture/005_001_Structured_Dynamic_Documents.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

