project:
  type: website

website:
  title: "MSB105"
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: "Home"
      - about.qmd
      - text: "Lectures"
        menu:
          - introduction/introduction.qmd
          - explore-data/explore-data.qmd
          - wrangle-data/wrangle-data.qmd
          - program/program.qmd


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

