project:
  type: website
  resources: 
    - introduction/reproducibility/reproducibility.bib

website:
  title: "MSB105"
  navbar:
    background: primary
    left:

      - href: index.qmd
        text: "Home"      
      - file: introduction/introduction.qmd
      - file: explore-data/explore-data.qmd
      - file: wrangle-data/wrangle-data.qmd
      - file: program/program.qmd
      - file: model/model.qmd
      - file: assignments/assignments.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

