---
title: "Innledende R notater"
format: html
lang: nb
editor: visual
---

## Innledning

Her er min aller første R kode.

```{r}
x <- 3 + 3
x
```

```{r}
# eller begge samtidig
(x <- 3 + 3)
```

```{r}
(x <- 13)
```

De fire regneartene

```{r}
(2/15)^0.25*exp(4) - 200
```

```{r}
x <- 2
(y <- 5)
```

```{r}
x + y
```

```{r}
x^y
```

```{r}
z <- x^y
```

```{r}
(z <- x + y)
```

```{r}
(x <- 13)
```

```{r}
z
```

```{r}
# definerer z på ny
# får nå oppdatert verdi der ny x verdi (13) er brukt
(z <- x + y)
```

```{r}
typeof(z)
```

```{r}
x <- 13L
y <- 5L
```

```{r}
z <- x + y
```

```{r}
typeof(z)
```

```{r}
#double
y <- 5
```

```{r}
# z double
z <- x + y
```

```{r}
# selv et enkelt tall er en vektor
is.vector(z)
```

```{r}
# vektor av heltall
(x <- c(2L, 8L, 9L, 21L:29L, 17L:12L))
```

```{r}
typeof(x)
```

```{r}
# 21 to 29 by 2
(x <- c(2L, 8L, 9L, seq(from = 21L, to = 29L, by = 2L), 17L:12L))
```

```{r}
(x <- c(2L, 8L, 9L, seq(from = 21L, to = 29L, by = 3L), 17L:12L))
```

```{r}
# from 29L to 21L by -3 L
(x <- c(2L, 8L, 9L, seq(from = 29L, to = 21L, by = -3L), 17L:12L))
```

```{r}
# vår x forskjellig fra den i slides
(y <- 6:(5 + length(x)))
```

```{r}
z <- x + y
```

```{r}
y <- c(y, 0.5 * x)
y
```

```{r}
x + y
```

```{r}
x <- c(x, 10)
```

```{r}
x + y
```

Et enklere eksempel

```{r}
(x <- 2:4)
```

```{r}
(y <- 10:12)
```

```{r}
(x + y)
```

```{r}
(y <- c(y, y + 0.5 * x))
```

```{r}
# automatisk replikering av korteste
# ingen warning
(x + y)
```

```{r}
y
```

```{r}
rep(x, 2)
```

Vi ser at x + y nå er x + y der x er replikert 2 ganger. Merk at R gjøre dette **UTEN** noen form for asvarsel.

```{r}
# legger til et tall (4) i fronten på x
(x <- c(4, x))
```

```{r}
# Nå er elngen av x 4 og lengden av y er 6. Tar vi nå x + y vil vi få en advarsel om at lengden av x ikke går opp i lengden av y
(x + y)
# men vi får svaret, x + y der den korteste x er replikert og man bruker de 
# verdiene som trengs for å matche y
```
