---
title: "Assignment 1 H25"
format: 
  html: default
  typst:
    papersize: a4
editor: visual
---

## Første oppgave (assignment) høsten 25

Ta utgangspunkt i malen i dokumentet [msb105_ass_1_25](./msb105_ass_1_25.txt) (arkiver med filendelsen qmd istedenfor .txt, malen finnes også på Canvas) og skriv et mini-paper på 3-4 sider med utgangspunkt i foredraget [«Robust and Reliable Science»](https://msb105.netlify.app/introduction/reproducibility/rr-science_h24#/title-slide). Dere finner en screencast av dette foredraget under [Panopto video](https://hvl.instructure.com/courses/32799/external_tools/1650) på kursets Canvas-sider.

På kursets Canvas-sider under [Ass1](https://hvl.instructure.com/courses/32799/files/folder/Ass1) i Filer finner dere apa7.csl, msb105_ass_1_25.qmd og reproducibility.bib som kan være til hjelp.

Oppgaven skal utføres individuelt og mot et Github repo.
Opprett først repo-et på Github før du lager et prosjekt i RStudio. `msb105Ass1` kan jo være et godt navn. Legg filene msb105_ass_1_24.qmd, apa7.csl og reproducibility.bib inn i ditt nye prosjekt.

Krav til oppgaven:

-   Det skal utføres minst 15 commits
    -   Med gode «commit messages» ;-)
-   Det skal være brukt minst 20 siteringer vha. siteringssystemet i Rstudio
    -   Fem skal dere har funnet selv, dvs. at de ikke er i reproducibility.bib
-   Det skal brukes minst to grener som skal merges inn i main
    -   Husk: skift først til main
    -   Så i Terminal: `git merge <gren-navn>`

Når dere er ferdige kan dere invitere meg (agjest) inn i repoet (eventuelt før hvis dere støter på problemer jeg kan hjelpe med 8-) )

Når jeg er invitert vil jeg gjøre en fork av repo-et, fikse eventuelle feil og skrive et kort dokument med kommentarer og tips.
Når jeg er ferdig vil dere få en «merge request» fra Github.

Det er lov å spørre om hjelp!
Hvis dere sender epost så bruk MSB105 i tittelen så er det mindre sjanse for at den blir oversett. Send direkte til ag@hvl.no og ikke via Canvas.
Får dere ikke respons så prøv på ny.
Det er dessverre litt «overload» på eposten min for tiden.

Oppstår det ting som alle kan ha bruk for å vite om vil jeg legge det ut som Melding her på Canvas.
