---
title: "Introduction"
editor: visual
---

This section will introduce you to the tools we will be using, RStudio (with Quarto), R, git, github and Zotero. It will try to give you an idea of what Data Sciences is and also teach you some classic R, give you an introduction to git and github and show you who to manage your references with Zotero.

## Presentations

-   [Intro](intro/intro.qmd)
-   [Undervisningsplan](undervisningsplan/undervisningsplan.qmd)
-   [Install Software](install-sw/install-sw.qmd)
-   [Structured Dynamic Documents](s-d-d/Structured-Dynamic-Documents.qmd)
    -   Documents:
        -   [Preferences RStudio](pref-setup-2022/ps2022.qmd)
        -   [Install R packages](install-R-packages/install-R-packages.qmd)
        -   [Illustrate Markdown](illustrate-markdown/illustrate-markdown.qmd)
        -   [Regression Tables](reg-tables/reg-tables.qmd)
    -   Other:
        -   [Stuff from lecture "Innledning R"](div-doc/Innledende-R-notater.qmd)
        -   [Connect RStudio to Github on mac](div-doc/rstudio-github.qmd)
-   [Git and Github](git-github/git-github.qmd)
-   [Very Short Intro to R](very-short-intro-r/very-short-intro-r.qmd)
    -   [Very Short Intro to R (as document)](very-short-intro-r/very-short-intro-r-document.qmd)
    -   [Notater fra forelesning (in Norwegian)](very-short-intro-r/innledende-R-notater-forelesning.qmd)

## Datasets

R has a lot of available datasets to practise with. The following document explains how to find what's available.

-   [Available Datasets](available-datasets/available_datasets.qmd)
