---
title: "Jørns funksjon"
output:
  html_document:
    df_print: paged
  html_notebook: default
  pdf_document: default
editor_options:
  chunk_output_type: inline
---

Load the libraries we need.

```{r setup}
library(ggplot2)
library(plotly)
library(COVID19)
```

Define the function.

```{r define-covid19qplot}
covid19qplot <- function(sel_country = "NOR", covid_data = all_data, date_from = "01-01-2020", sidebyside = T) {
  red_data <- covid_data[covid_data$date >= as.Date(date_from),]
#  sel_country <- country
  lag_num <- 1
  sidecol <- ifelse(sidebyside == T, 1, 2)
  main_title <- list(cases = paste("Country:", sel_country), deaths = paste("Country:", sel_country))

#browser()
  
  sel_data_2 <- subset(red_data, id %in% sel_country)[, c(1, 2, 4, 6)]
  sel_data_2$new_cases <- c(NA, diff(sel_data_2$confirmed, lag = lag_num))
  sel_data_2$new_deaths <- c(NA, diff(sel_data_2$deaths, lag = lag_num))
# Drop the first date for every country since diff will produce NAs
  sel_data_2 <- sel_data_2[sel_data_2$date > sel_data_2$date[1],]

  # Plot data
  names(sel_data_2)
  a <- qplot(data = sel_data_2, geom = "area", x = date, y = new_cases, main = sel_country)
  b <- qplot(data = sel_data_2, geom = "area", x = date, y = new_deaths, main = sel_country)
  # grid.arrange(a, b, ncol=2)
  subplot(a, b)
}
```

Run the function over selected countries.

```{r}
all_data <- covid19()
# View(all_data)
# countries <- unique(all_data$id)
sel_countries <- c("NOR", "FIN", "ESP", "SWE", "USA")
date_from_sel <- "01-01-2020"
plot_obj <- list()
for (country in sel_countries) {
  print(country)
  plot_obj_cou <- covid19qplot(country, covid_data = all_data, date_from = "01-01-2020", sidebyside = T)
  plot_obj <- list(plot_obj, plot_obj_cou)
}
print(plot_obj)
```

